### ISSUE TITLE
0.0.13: build `sphinx-design` documentation fails

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-design#54]
### Describe the bug

Looks like builkd `sphinx-design`  documentation fails.

### Reproduce the bug

Run `python3 setup.py build_sphinx -b man` command in source tree.

### List your environment

List of installed modules in build env
```console
Package                    Version
-------------------------- --------------
chardet                    4.0.0
cycler                     0.11.0
dbus-python                1.2.18
distro                     1.6.0
extras                     1.0.0
fixtures                   3.0.0
fonttools                  4.29.1
gpg                        1.16.0-unknown
jupyter-packaging-test-foo 0.1
kiwisolver                 1.3.2
libcomps                   0.1.18
lit                        13.0.1
lxml                       4.7.1
matplotlib                 3.5.1
meson                      0.61.1
numpy                      1.22.0
olefile                    0.46
packaging                  21.3
pbr                        5.8.0
Pillow                     9.0.1
pip                        21.3.1
pycairo                    1.20.1
PyGObject                  3.42.0
pyparsing                  3.0.7
python-dateutil            2.8.2
rpm                        4.17.0
six                        1.16.0
testtools                  2.5.0
```

**Comment by kloczek** [comment]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
making output directory... done
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'deflist', 'substitution', 'html_image'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=['loremipsum'], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 10 added, 0 changed, 0 removed
entering code: StateBlock(line=0,level=0,tokens=0), 0, 72, False
entering fence: StateBlock(line=0,level=0,tokens=0), 0, 72, False
entering blockquote: StateBlock(line=0,level=0,tokens=0), 0, 72, False
entering code: StateBlock(line=2,level=0,tokens=1), 2, 72, False
entering fence: StateBlock(line=2,level=0,tokens=1), 2, 72, False
entering blockquote: StateBlock(line=2,level=0,tokens=1), 2, 72, False
entering hr: StateBlock(line=2,level=0,tokens=1), 2, 72, False
entering list: StateBlock(line=2,level=0,tokens=1), 2, 72, False

[..]

entering heading: StateBlock(line=0,level=0,tokens=0), 0, 1, False
entering lheading: StateBlock(line=0,level=0,tokens=0), 0, 1, False
entering paragraph: StateBlock(line=0,level=0,tokens=0), 0, 1, False

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinxdesign.1 { get_started grids cards dropdowns tabs badges_buttons additional css_variables css_classes } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 1034, in replace_self
    assert not self[att], \
AssertionError: Losing "classes" attribute: ['sd-stretched-link']
The full traceback has been saved in /tmp/sphinx-err-nz7jbovm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/sphinx-err-nz7jbovm.log
# Sphinx version: 4.3.2
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   grids
#   cards
#   dropdowns
#   tabs
#   badges_buttons
#   additional
#   css_variables
#   css_classes
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.16.1) from /usr/lib/python3.8/site-packages/myst_parser/__init__.py
#   sphinx_design (0.0.13) from /home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/sphinx_design/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 175, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 99, in write
    self.env.resolve_references(largetree, docname, self)
  File "/usr/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 569, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/usr/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 581, in apply_post_transforms
    transformer.apply_transforms()
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 43, in apply
    self.run(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 121, in run
    node.replace_self(newnodes)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 1034, in replace_self
    assert not self[att], \
AssertionError: Losing "classes" attribute: ['sd-stretched-link']
```

**Comment by pradyunsg** [comment]
> python3 setup.py build_sphinx -b man

Using `setup.py build_sphinx` is not supported by this project. You need to build the docs using `tox`. See the following section for the list of tox target names:

https://github.com/executablebooks/sphinx-design/blob/6a412a18abe310b0ceba258a2867bd183214cc27/tox.ini#L22

**Comment by kloczek** [comment]
This issue has nothing to do with using sphinx<>setuptools integration.
In mean time I've switched in almost all my rpm spec files building documentation from using sphinx<>setuptools integration to straight using sphinx-build
To use it it is necessary to apply patch:
```patch
--- a/docs/conf.py~     2021-10-27 21:07:30.000000000 +0000
+++ b/docs/conf.py      2022-04-20 20:50:00.767110407 +0000
@@ -1,5 +1,7 @@
 """Configuration file for the Sphinx documentation builder."""
 import os
+import sys
+sys.path.insert(0, os.path.abspath('..'))

 project = "Sphinx Design"
 copyright = "2021, Executable Book Project"
```
That patch allows to build documentation without tox. Documentation should be always build against source tree and not against installed module.
With that parch build sphinx fails the same way
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
myst v0.17.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence', 'deflist', 'substitution', 'html_image'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=['http', 'https', 'mailto', 'ftp'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=['loremipsum'], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 10 added, 0 changed, 0 removed
reading sources... [100%] tabs
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinxdesign.1 { get_started grids cards dropdowns tabs badges_buttons additional css_variables css_classes } failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 350, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 540, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 93, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 120, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-xaojs19b.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
And at the and .. I've just tested using tox and it fails
```console
[tkloczko@devel-g2v sphinx-design-0.0.13]$ tox -e docs-update-rtd
docs-update-rtd create: /home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/.tox/docs-update-rtd
docs-update-rtd develop-inst: /home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13
docs-update-rtd installed: alabaster==0.7.12,attrs==21.4.0,Babel==2.10.1,certifi==2021.10.8,charset-normalizer==2.0.12,docutils==0.16,idna==3.3,imagesize==1.3.0,importlib-metadata==4.11.3,Jinja2==3.1.1,markdown-it-py==1.1.0,MarkupSafe==2.1.1,mdit-py-plugins==0.2.8,myst-parser==0.15.2,packaging==21.3,Pygments==2.11.2,pyparsing==3.0.8,pytz==2022.1,PyYAML==6.0,requests==2.27.1,snowballstemmer==2.2.0,Sphinx==4.5.0,# Editable install with no version control (sphinx-design==0.0.13),-e /home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13,sphinx-rtd-theme==0.5.2,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,urllib3==1.26.9,zipp==3.8.0
docs-update-rtd run-test-pre: PYTHONHASHSEED='1077553518'
docs-update-rtd run-test: commands[0] | sphinx-build -nW --keep-going -b html docs/ docs/_build/html
Running Sphinx v4.5.0
making output directory... done
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'deflist', 'substitution', 'html_image'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=['loremipsum'], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 10 source files that are out of date
updating environment: [new config] 10 added, 0 changed, 0 removed
reading sources... [ 10%] additional
reading sources... [ 20%] badges_buttons
reading sources... [ 30%] cards
reading sources... [ 40%] css_classes
reading sources... [ 50%] css_variables
reading sources... [ 60%] dropdowns
reading sources... [ 70%] get_started
reading sources... [ 80%] grids
reading sources... [ 90%] index
reading sources... [100%] tabs

/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/additional.md:12: ERROR: Unknown directive type "article-info".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/additional.md:22: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:1: ERROR: Unknown interpreted text role "octicon".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:10: ERROR: Unknown interpreted text role "bdg".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:11: ERROR: Unknown interpreted text role "bdg-primary".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:11: ERROR: Unknown interpreted text role "bdg-primary-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:12: ERROR: Unknown interpreted text role "bdg-secondary".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:12: ERROR: Unknown interpreted text role "bdg-secondary-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:13: ERROR: Unknown interpreted text role "bdg-success".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:13: ERROR: Unknown interpreted text role "bdg-success-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:14: ERROR: Unknown interpreted text role "bdg-info".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:14: ERROR: Unknown interpreted text role "bdg-info-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:15: ERROR: Unknown interpreted text role "bdg-warning".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:15: ERROR: Unknown interpreted text role "bdg-warning-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:16: ERROR: Unknown interpreted text role "bdg-danger".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:16: ERROR: Unknown interpreted text role "bdg-danger-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:17: ERROR: Unknown interpreted text role "bdg-light".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:17: ERROR: Unknown interpreted text role "bdg-light-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:18: ERROR: Unknown interpreted text role "bdg-dark".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:18: ERROR: Unknown interpreted text role "bdg-dark-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:20: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:37: ERROR: Unknown interpreted text role "bdg-link-primary".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:39: ERROR: Unknown interpreted text role "bdg-link-primary-line".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:41: ERROR: Unknown interpreted text role "bdg-ref-primary".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:43: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:65: ERROR: Unknown directive type "button-link".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:68: ERROR: Unknown directive type "button-link".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:72: ERROR: Unknown directive type "button-link".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:77: ERROR: Unknown directive type "button-link".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:82: ERROR: Unknown directive type "button-link".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:87: ERROR: Unknown directive type "button-ref".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:91: ERROR: Unknown directive type "button-ref".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:97: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:114: ERROR: Unknown directive type "button-ref".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:123: ERROR: Unknown directive type "button-ref".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:132: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:186: ERROR: Unknown interpreted text role "octicon".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:188: ERROR: Unknown directive type "tab-set-code".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:197: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:214: ERROR: Unknown directive type "tab-set-code".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/badges_buttons.md:223: ERROR: Unknown interpreted text role "fas".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:9: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:16: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:33: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:41: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:57: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:80: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:115: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:136: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:142: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:149: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:168: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:176: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:184: ERROR: Unknown directive type "card".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:201: ERROR: Unknown directive type "card-carousel".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/cards.md:221: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:8: ERROR: Unknown directive type "div".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:12: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:139: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:189: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:239: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/css_classes.md:278: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:9: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:13: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:17: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:23: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:41: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:47: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:57: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/dropdowns.md:68: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/get_started.md:3: ERROR: Unknown directive type "article-info".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/get_started.md:31: ERROR: Unknown directive type "tab-set".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:15: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:32: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:48: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:74: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:83: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:102: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:113: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:124: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:145: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:163: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:182: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:202: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/grids.md:257: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/index.md:7: ERROR: Unknown directive type "div".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/index.md:94: ERROR: Unknown directive type "grid".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:8: ERROR: Unknown directive type "tab-set".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:20: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:41: ERROR: Unknown directive type "tab-set".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:57: ERROR: Unknown directive type "tab-set".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:73: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:93: ERROR: Unknown directive type "tab-set".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:117: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/docs/tabs.md:139: ERROR: Unknown directive type "grid".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 10%] additional
writing output... [ 20%] badges_buttons
writing output... [ 30%] cards
writing output... [ 40%] css_classes
writing output... [ 50%] css_variables
writing output... [ 60%] dropdowns
writing output... [ 70%] get_started
writing output... [ 80%] grids
writing output... [ 90%] index
writing output... [100%] tabs

generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 95 warnings.
ERROR: InvocationError for command /home/tkloczko/rpmbuild/BUILD/sphinx-design-0.0.13/.tox/docs-update-rtd/bin/sphinx-build -nW --keep-going -b html docs/ docs/_build/html (exited with code 1)
docs-update-rtd run-test-post: commands[0] | echo 'open docs/_build/html/index.html'
open docs/_build/html/index.html
_________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   docs-update-rtd: commands failed
```

Looks like you've did not try to reproduce what I've reported and just assumed that it must be related to use sphinx<>setuptools integration 😞
